"""JOBS-6 SUBMISSION — the outward, irreversible step.

⚠️ **NO SUBMISSION DRIVER EXISTS YET.** This module assembles and validates a submission package and
then, with no driver registered, returns `manual_required`. That is a deliberate first-class outcome
(design § 7), not a stub that will silently start working.

**Why there is no driver: neither ATS offers a candidate-side API.**
Greenhouse's application POST requires HTTP Basic Auth whose username is *the employer's* API key
("found on the API Credentials page"), and Lever's apply POST needs a key generated by *the
employer's* Super Admin. Those endpoints exist so an employer can build their own careers page. A
candidate has neither credential, so there is no lawful programmatic path — submission must drive
the public web form, which means a browser, which this service does not have.

That architecture decision belongs to the operator, so it is surfaced rather than guessed at.

What this module DOES enforce, and why each matters:

- **Approval is required.** Only an application the operator approved (or edited) may be submitted.
  Anything else — drafted, awaiting_approval, expired, rejected — is refused.
- **Idempotency.** Submitting twice to one req is worse than not submitting: it looks careless to
  the employer and cannot be undone. Guarded in the DB (`UNIQUE (listing_id)`) and again here.
- **Answer bank, EXACT match only** (operator decision 4). A screening question is answered only if
  its normalized text is already in the bank. No LLM decides two questions "mean the same thing" — a
  confident near-match is exactly how a wrong answer gets submitted under someone's name.
- **No CAPTCHA solving. No account creation.** Both are out of scope by design, permanently.
- **Evidence or it did not happen.** A submission with no stored confirmation artifact is recorded
  as NOT submitted.
"""
from __future__ import annotations

import re
from typing import Protocol

import structlog

log = structlog.get_logger()

APPROVED_STATUSES = frozenset({"approved", "edited"})
SUPPORTED_ATS = frozenset({"greenhouse", "lever"})


class SubmissionDriver(Protocol):
    """What a real submitter must provide. Intentionally narrow."""

    async def submit(self, package: dict) -> dict:
        """Return {'ok': bool, 'evidence': dict, 'failure_reason': str | None}."""
        ...


_DRIVER: SubmissionDriver | None = None


def register_driver(driver: SubmissionDriver | None) -> None:
    """Install the submission driver. Called by nothing in production today."""
    global _DRIVER
    _DRIVER = driver


def normalize_question(q: str) -> str:
    """Normalize for EXACT matching: case, whitespace and trailing punctuation only.

    Deliberately conservative. Anything cleverer (stemming, synonyms, embeddings) turns a miss into
    a confident wrong answer, and a wrong answer is submitted under the operator's name.
    """
    s = re.sub(r"\s+", " ", (q or "")).strip().lower()
    return s.rstrip(" ?:.*")


def answer_for(question: str, bank: dict[str, str]) -> str | None:
    return bank.get(normalize_question(question))


def resolve_answers(questions: list[str], bank: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    """(answered, unanswered). ANY unanswered question makes the whole application manual."""
    answered, missing = {}, []
    for q in questions or []:
        a = answer_for(q, bank)
        if a is None:
            missing.append(q)
        else:
            answered[q] = a
    return answered, missing


def ats_of(canonical_url: str) -> str | None:
    u = (canonical_url or "").lower()
    if "greenhouse.io" in u:
        return "greenhouse"
    if "lever.co" in u:
        return "lever"
    if "ashbyhq.com" in u:
        return "ashby"
    if "myworkdayjobs.com" in u or "workday" in u:
        return "workday"
    return None


def prepare(application: dict, questions: list[str], bank: dict[str, str]) -> dict:
    """Assemble + validate a submission package. Never touches the network.

    Returns {'ok', 'outcome', 'reason', 'package'} where outcome is one of
    'ready' | 'manual_required' | 'refused'.
    """
    status = application.get("status")
    if status not in APPROVED_STATUSES:
        return {"ok": False, "outcome": "refused",
                "reason": f"not approved (status={status!r}); only {sorted(APPROVED_STATUSES)} may submit",
                "package": None}
    if application.get("submitted_at"):
        return {"ok": False, "outcome": "refused",
                "reason": "already submitted — submitting twice to one req is not recoverable",
                "package": None}

    url = application.get("canonical_url") or ""
    ats = ats_of(url)
    if ats not in SUPPORTED_ATS:
        return {"ok": False, "outcome": "manual_required",
                "reason": f"unsupported ATS ({ats or 'unknown'}); only {sorted(SUPPORTED_ATS)} are in scope",
                "package": None}

    answered, missing = resolve_answers(questions, bank)
    if missing:
        return {"ok": False, "outcome": "manual_required",
                "reason": "screening questions with no exact answer-bank match: "
                          + "; ".join(missing[:5]),
                "package": None}

    cv = application.get("tailored_cv_path")
    if not cv:
        return {"ok": False, "outcome": "manual_required",
                "reason": "no tailored CV artifact to upload", "package": None}

    return {"ok": True, "outcome": "ready", "reason": None,
            "package": {"ats": ats, "url": url, "cv_path": cv, "answers": answered,
                        "application_id": application.get("id")}}


async def submit(application: dict, questions: list[str], bank: dict[str, str]) -> dict:
    """Prepare, then submit if a driver is installed. Returns the outcome dict."""
    prepared = prepare(application, questions, bank)
    if not prepared["ok"]:
        return {**prepared, "submitted": False, "evidence": {}}

    if _DRIVER is None:
        # The honest outcome. Not a silent success, not a crash.
        return {"ok": False, "outcome": "manual_required", "submitted": False, "evidence": {},
                "reason": "no submission driver installed — neither Greenhouse nor Lever exposes a "
                          "candidate-side application API, so this step needs a browser driver "
                          "(operator decision pending)",
                "package": prepared["package"]}

    res = await _DRIVER.submit(prepared["package"])
    evidence = res.get("evidence") or {}
    if not res.get("ok"):
        # A driver may DECLARE its outcome. `manual_required` is not a failure — it is the designed
        # result when the form asks something the operator has not answered, and flattening it to
        # "failed" would make a correct refusal look like a broken run.
        return {"ok": False, "outcome": res.get("outcome") or "failed", "submitted": False,
                "evidence": evidence,
                "reason": res.get("failure_reason") or "driver reported failure",
                "package": prepared["package"]}
    if res.get("clicked") and not res.get("ok"):
        # We clicked and cannot tell what happened. NOT submitted (we will not claim what we cannot
        # evidence) — but emphatically not retryable either, because the employer may already hold
        # the application. The only safe next actor is a human.
        return {"ok": False, "outcome": "needs_verification", "submitted": False,
                "evidence": evidence, "reason": res.get("failure_reason") or
                "submit clicked, outcome unknown", "package": prepared["package"]}
    if not evidence:
        # A claimed submission with no artifact is treated as NOT submitted. Believing an unevidenced
        # claim is how the tracker drifts away from reality in the direction that looks good.
        return {"ok": False, "outcome": "failed", "submitted": False, "evidence": {},
                "reason": "driver reported success with no confirmation artifact — treated as NOT submitted",
                "package": prepared["package"]}
    return {"ok": True, "outcome": "submitted", "submitted": True, "evidence": evidence,
            "reason": None, "package": prepared["package"]}
